version: "3.9"  # optional since v1.27.0
services:
  dotnet:
    image:
      mcr.microsoft.com/dotnet/samples:aspnetapp
    ports:
      - "8000:80"
    links:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:latest
